### ISSUE TITLE
Effect Conditional Colouring

### ISSUE THREAD

**Issue by JacobsonMT** [PavlidisLab/ndb#14]
Conditional colouring on the effect column, similar to CADD.

**Comment by JacobsonMT** [comment]
Colours might be confusing situation, need better solution. Consider adding LOF symbol next to effect instead (See Issue #16).

**Comment by mbelmadani** [comment]
LoF information is now in the database and is currently shown as plain text (yes/no/unknown). We can replace the text by a symbol if preferred. 

Another idea: Match color coding between LoF, CADD and Effect type to visualize agreement/disagreement between different reports. E.g., a Low cadd (green) might have a medium effect (e.g. nonsynonymous snv ) (yellow) reported as a LoF in the paper (red). 

Ideally, most of these would be consistent (especially since CADD partially depends on the effect type, and the LoF annotation sometimes as well), but cases where there's disagreement will be emphasized by color mismatch.

**Comment by mbelmadani** [comment]
Effect has been coloured for some time now.
