### ISSUE TITLE
Multiple database configuration files

### ISSUE THREAD

**Issue by tesar-stepan** [PavlidisLab/ndb#37]
There are several configuration files providing almost the same information:
 * db.properties / ndb.properties
 * context.xml - in ndb/src/main/webapp/META_INF/
 * db.config - for paperpipe, in ndb/etc/paperpipe/pipeline
 * settings.xml - for maven, in ~/.m2/

**Comment by JacobsonMT** [comment]
Here's a breakdown for the following files:

db.properties: Defines log in credentials for MySQL JNDI's that are located in tomcat context files. Multiple apps may share this file.
ndb.properties: General properties for ndb, contains (among other things) the name of the set of credentials from db.properties to be used for this app.
context.xml: Defines connection information for connecting to specific databases (not including log in credentials). Such as location, driver, eviction schedule, threads.
settings.xml: Contains general properties for maven, this contains information similar to above because maven has to connect to databases to initialise and import data to test databases  ( as well as possibly other things)
db.config: Not sure, need input from @mbelmadani .

I can see some overlap between settings.xml and db.properties. It map be possible to include sensitive information in maven settings only and have it write to relevant locations in the application on build. That would remove the need for credentials in db.properties.

However, completely removing db.properties also disallows having a central file referencing all available database JNDIs. If we want to define database JNDIs on a tomcat basis as opposed to application level (for better thread pooling, for example) it seems necessary to have a central naming scheme so each app doesn't need to go looking for JNDI configuration files to find their name.

**Comment by mbelmadani** [comment]
db.config is specific to the paper import pipeline. It's not using the project's configs in case one wants to update a database that's not being ran by the application.

**Comment by mbelmadani** [comment]
Closing for now as none of these are completely redundant.
